"""empty message

Revision ID: 24389bfa68f2
Revises: 84146c814a02
Create Date: 2022-01-11 14:20:13.352214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24389bfa68f2'
down_revision = '84146c814a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'companynames', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companynames', type_='foreignkey')
    # ### end Alembic commands ###
