"""empty message

Revision ID: 70c16c6a1847
Revises: 24389bfa68f2
Create Date: 2022-01-11 16:19:17.115493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c16c6a1847'
down_revision = '24389bfa68f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    op.drop_table('tags')
    op.drop_table('company_tags')
    op.drop_table('companynames')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companynames',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='companynames_company_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='companynames_pkey')
    )
    op.create_table('company_tags',
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tags_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='company_tags_company_id_fkey'),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], name='company_tags_tags_id_fkey'),
    sa.PrimaryKeyConstraint('company_id', 'tags_id', name='company_tags_pkey')
    )
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lang', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tags_pkey')
    )
    op.create_table('companies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='companies_pkey')
    )
    # ### end Alembic commands ###
