"""empty message

Revision ID: 84146c814a02
Revises: ae72eeaaa4f3
Create Date: 2022-01-11 13:45:03.010561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84146c814a02'
down_revision = 'ae72eeaaa4f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CompanyNames')
    op.drop_table('companies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='companies_pkey')
    )
    op.create_table('CompanyNames',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"CompanyNames_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='CompanyNames_pkey')
    )
    # ### end Alembic commands ###
