"""empty message

Revision ID: ae72eeaaa4f3
Revises: 2cd568bbbbe1
Create Date: 2022-01-10 13:55:51.437755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae72eeaaa4f3'
down_revision = '2cd568bbbbe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dogs', sa.Column('breed', sa.String(length=100), nullable=True))
    op.drop_column('dogs', 'sex')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dogs', sa.Column('sex', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('dogs', 'breed')
    # ### end Alembic commands ###
